language: node_js
node_js:
- 12
matrix:
  fast_finish: true
addons:
  apt:
    packages:
    - parallel
before_install:
- yarn global add webpack-cli
- yarn --version
before_script:
- yarn install
script:
- 'yarn build

  '
deploy:
  provider: releases
  api_key: 76d9f19daddfcb68331c4c08b553ae4d463852eb
  file: 'deploy:'
  on:
    repo: ochorocho/syspass-addon
  skip_cleanup: 'true'
