language: node_js
node_js:
  - 12

matrix:
  fast_finish: true

sudo: false

addons:
  apt:
    packages:
      - parallel

before_install:
  - yarn global add webpack-cli
  - yarn --version

before_script:
  - yarn install

script:
  - >
    yarn build

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - web-ext-artifacts/*
  skip_cleanup: true
  on:
    repo: https://github.com/ochorocho/syspass-addon
    tags: true
